// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRn3jb-hjO3PwgvLjD7P7e005j3-41aX8',
    appId: '1:70865333096:web:449cf865dff6d71b35c4dd',
    messagingSenderId: '70865333096',
    projectId: 'fir-coba-f2482',
    authDomain: 'fir-coba-f2482.firebaseapp.com',
    storageBucket: 'fir-coba-f2482.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EjE3dWd1gBOD_-yjIWpQsmtHAqPRfXQ',
    appId: '1:70865333096:android:c90948d24ae2552535c4dd',
    messagingSenderId: '70865333096',
    projectId: 'fir-coba-f2482',
    storageBucket: 'fir-coba-f2482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQiAgh8mWCNeLJI8D6bHRvqlv2jWOpX1U',
    appId: '1:70865333096:ios:396986fa7398f34035c4dd',
    messagingSenderId: '70865333096',
    projectId: 'fir-coba-f2482',
    storageBucket: 'fir-coba-f2482.appspot.com',
    iosClientId: '70865333096-9nfkvvn69hork4eonp2me5lqihlfbo7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasAmbw196',
  );
}
